### ISSUE TITLE
hbv2gfa segmentation fault

### ISSUE THREAD

**Issue by ethering** [bioinfologics/w2rap-contigger#19]
Hi,
I've run w2rap-contigger to step 4 and then run hbv2gfa as follows: 

export OMP_PROC_BIND=spread
export MALLOC_PER_THREAD=1
source w2rap-a43f5a0;
source gcc-5.2.0;
hbv2gfa -o polecat_k180_out -i polecat_k180.large_K.clean --stats_only 1 -g 2400000

Here’s the stdout:
hbv2gfa from w2rap-contigger
Reading graph and paths...
   DONE!
=== Graph stats ===
Canonical graph sequences size: 46916876167429
 
 
And here’s the  stderr:
/var/spool/PBS/mom_priv/jobs/68505.UVL00000253-P000.SC: line 7: 331372 Segmentation fault hbv2gfa -o polecat_k180_out -i polecat_k180.large_K.clean --stats_only 1 -g 2400000

I've also tried without --stats_only, but I get the same Segmentation fault.

**Comment by bjclavijo** [comment]
closing this, it should not be relevant anymore.

**Comment by ljyanesm** [comment]
Fixed for master with abe791c
