### ISSUE TITLE
incomplete record

### ISSUE THREAD

**Issue by jdmontenegro** [bioinfologics/w2rap-contigger#22]
Hi all,
I am trying to run w2rap-contigger, with the following command line:

w2rap-contigger -t 36 -m 800 --from_step 1 --to_step 7 -r file_1.fastq,file_2.fastq -o Assembly/w2rap/EC -p Assembly_K200 -s 200 --dump_perf 1

 but I get the following error at the start of the assembly:

"See incomplete record in faile1.fastq ot file2.fastq"

I have checked both files and there are no empty lines nor incomplete records in these. Both files have the same length and the same names for paired reads. What else could cause the getline to fail?

I look forward to hearing from you.

Best regards,

Juan Montenegro

**Comment by ljyanesm** [comment]
Hi,

Are you still experiencing this error? The error message you mention can happen not only if the files are corrupt but also if there were issues with the filesystem whilst reading them.

Kindly,

**Comment by jdmontenegro** [comment]
Hi. I guess that must have happened, because I resubmitted with the
original file and it worked correctly this time. The only problem was the
amount of memory used. It used more than 750gb before next extracting
kmers, do you have any development branch that extracts kmers immediately
after reading the files and does not load de the reads into memory? Or is
it essential to keep the reads in memory?

Regards,

Juan Montenegro

**Comment by ljyanesm** [comment]
Hi,

The master branch has a mode for using disk batches, the "-d" flag can help reduce the maximum required memory. A value of 16 should be enough.

Kindly,
Luis
