### ISSUE TITLE
w2rap-contiger with 150bp pe library

### ISSUE THREAD

**Issue by StephanHolgerD** [bioinfologics/w2rap-contigger#24]
Hey,
is it possible to use the w2rap-contiger with 2 x 150 bp paired end library or is there a minimum for the read length? 
I tried to assemble a smaller genome with 2 x 150 bp paired end library but after step 5 I always get :

Fatal error (pid=27838) at Mi Mai 03 14:17:59 2017:
Illegal value for CP_MAX_QDIFF.

I am not sure whether this problem arise because of  the read length or because of a installation problem.

**Comment by bjclavijo** [comment]
Hi Stephan. That is not a problem with read length, but rather your qualities having incorrect values (or extreme ones).
Which kind of files are you using as input files? Fastq? can you paste the command line you used too? I would recommend running fastqc or something like that to get an idea how your files look like.

**Comment by StephanHolgerD** [comment]
Hey,
I provided gzipped fastq files as input. But I checked the quality values with fastqc and i also trimmed my reads using trimmomatic, before I try to start W2rap-contiger.

here is my starting commandline

`:~$ '/home/test/Programme/w2rap-contigger/bin/w2rap-contigger' -o d1131_cat_30_nohead_130 -p d1131_cat_30_nohead_130 -r '/media/test/daten/Stephan/Genom/02_processed_Data/d1131_cat_30_minlen130/d1131_cat_30_nohead_130_1P.fq.gz','/media/test/daten/Stephan/Genom/02_processed_Data/d1131_cat_30_minlen130/d1131_cat_30_nohead_130_2P.fq.gz' -K 80 -t 40`

**Comment by Vickywzy** [comment]
Hey,
I also have this error , can you tell me how to solve this error?

**Comment by jonwright99** [comment]
Can you send me the command line you're using to start w2rap and paste in a few lines of your FASTQ files?

**Comment by kokyriakidis** [comment]
@jonwright99 Does w2rap-contiger support gz files as input? How do I use multiple fastq.gz files as input? Just adding multiple times the -r parameter?

**Comment by jonwright99** [comment]
We've not added functionality to use gzipped files yet so your FASTQs must be unzipped for now. For multiple files use a single -r parameter like so; -r file1.fastq,file2.fastq,file3.fastq,file4.fastq

**Comment by kokyriakidis** [comment]
@jonwright99 
1) So, I have to interleave them? There are 4 libraries and are in _1.fastq _2.fastq format. 
2) The insert sizes of the libraries are i) 240bp ii) 300bp iii) 420bp iv) 800bp. Do you recommend using all of them? Or should I exclude the small ones?

**Comment by jonwright99** [comment]
w2rap has no concept of separate libraries as yet (another improvement we hope to make in the future). We generally sequence one library with 600-700bp insert size to around 45x coverage with 250bp reads. For your data I would include the largest libraries until you have required coverage. 100bp reads are pretty short so depending on the complexity of your genome, w2rap may struggle to build the graph.

**Comment by kokyriakidis** [comment]
1) So, should I interleave each of the 2 libraries (420bp and 800bp) and put them in the program as file1.fastq (420bp) and file2.fastq(800bp)? Or should I concatenate the fastq files (420bp and 800bp) and input file1_R1.fastq and file1_R2.fastq?

2) This is the k-mer histogram (using KAT) from the 2 libraries (420bp and 800bp). Should I set min_frequency =9 at the w2rap contiger? 

![kiwi_pe_hist](https://user-images.githubusercontent.com/33731293/50558272-2cd22080-0cf5-11e9-946e-d27348b8d6a1.png)

**Comment by kokyriakidis** [comment]
@jonwright99 Happy new year!
I am trying to do the LMP Processing but when I try to run  lmp_processing <read_file_list> <ncpus>  it throws me errors like:

```
 File "w2rap/lmp_processing", line 100
    print "\n#### w2rap LMP processing ####\n"
                                             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("\n#### w2rap LMP processing ####\n")?
```
But this is not the only one. When I edit the script and put parenthesis in every print command, it throws me other errors! Do you know what is happening?

**Comment by bjclavijo** [comment]
That script is python2 and you're probably using python3?

Best,

bj

**Comment by kokyriakidis** [comment]
@jonwright99 @bjclavijo I am at the stage of "prepare -> map -> scaff" pipeline but I cannot find the _prepare, s_map and s_scaff files in order to run them. What am I missing?

**Comment by jonwright99** [comment]
Thanks for the feedback. I've added a note to the README to say the LMP processing script is written in Python 2.7.

The s_prepare, s_map and s_scaff binaries need to be compiled from source. There is a Makefile in w2rap/deps/soap_scaffolder which should do the trick (I should also add this into the README)

**Comment by kokyriakidis** [comment]
@jonwright99  I deleted my comment on s_prepare, s_map and s_scaff cause I realized that I had to build them from source after searching all the folders. So you could also add it in the README for future reference.

**Comment by bjclavijo** [comment]
Closing here as the remaining questions are for w2rap pipeline now.
