### ISSUE TITLE
Step 3 crashed

### ISSUE THREAD

**Issue by yloemie** [bioinfologics/w2rap-contigger#35]
Hi team,

first thank for your work. My job at step 3 everytime. I have tried with different Kmer size.

Here my log : 

--== Step 3: Repathing to second (large K) graph ==--
/bin/sh: 1: set: Illegal option -o pipefail
Fri Aug 17 16:50:02 2018: beginning repathing 21722531 edges from K=60 to K2=60
Fri Aug 17 16:50:02 2018: constructing places from 133868092 paths
Fri Aug 17 16:50:03 2018: 118287130 / 133868092 reads pathed, 82739270 spanning junctions
Fri Aug 17 16:51:57 2018: sorting 118287130 places
Fri Aug 17 16:54:43 2018: 41782245 unique places
Fri Aug 17 16:54:43 2018: building all
Fri Aug 17 16:58:25 2018: calling LongReadsToPaths
Killed

So first I have this error (illegal option -o pipefail) and after that it just crash with this comment "killed".

I have checked my system log : 
Out of memory: Kill process 10849 (w2rap-contigger) score 964 or sacrifice child

So do you have an idea how to reduce the memory used for step 3?

I will try to normalize my libraries (reducing my number of reads).

Thanks,

Yann

**Comment by bjclavijo** [comment]
The upcoming release of w2rap-contigger uses less memory, but otherwise it is not recommended to run it if there is not enough memory for the dataset.
