### ISSUE TITLE
denoising Illumina reads

### ISSUE THREAD

**Issue by mictadlo** [bioinfologics/w2rap-contigger#37]
Hi,
Do you recommend to do denoising Illumina reads e.g. with any of [khmer](https://khmer-recipes.readthedocs.io/en/latest/) recipes or any other tool?

Thank you in advance,

Michal

**Comment by jonwright99** [comment]
We generally don't do any QC before contig assembly other than the steps we outline in the w2rap pipeline (https://github.com/bioinfologics/w2rap/), ie. FASTQC to check read quality, a kmer histogram to check coverage mapping reads to check the insert size distribution.
