### ISSUE TITLE
cannot find -llib

### ISSUE THREAD

**Issue by stsmall** [bioinfologics/w2rap-contigger#4]
Hi,
I followed the instructions on the github page. I also have jemalloc installed. When I run:
cmake -D CMAKE_CXX_COMPILER=g++ -D MALLOC_LIBRARY=/afs/crc.nd.edu/user/s/ssmall2/programs_that_work/jemalloc-4.2.1/lib
It finishes without an error. 
When I run "make -j 4" it get to about 90% then starts printing the error:
/usr/bin/ld: cannot find -llib

cmake: 3.4.1 
gcc: 4.8.2
operating system: gnu/linux

Probably something on my end, but before I bother IT I thought I would check here. Also in case someone has a similar issue in the future.
thank you!
-scott

**Comment by gonzalogacc** [comment]
Hi scott!
Seems to be a linker problem. 
Please try to compile with gcc 5.1+ and let me know how it goes.
Best.
Gonza.-

**Comment by stsmall** [comment]
Hi Gonza,
I tried it again with gcc 5.2.0. Same error (here are the lines from 83% onward):

[ 83%] Building CXX object CMakeFiles/01_unipaths.dir/src/paths/long/ShortKmerReadPather.cc.o
[ 83%] Building CXX object CMakeFiles/02_qgraph.dir/src/FastaVerifier.cc.o
[ 84%] Building CXX object CMakeFiles/02_qgraph.dir/src/Misc.cc.o
[ 84%] Building CXX object CMakeFiles/02_qgraph.dir/src/paths/long/BuildReadQGraph.cc.o
[ 85%] Linking CXX executable bin/03_clean
/usr/bin/ld: cannot find -llib
collect2: error: ld returned 1 exit status
make[2]: *** [bin/03_clean] Error 1
make[1]: *** [CMakeFiles/03_clean.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 85%] Building CXX object CMakeFiles/02_qgraph.dir/src/paths/long/ExtendReadPath.cc.o
[ 85%] Building CXX object CMakeFiles/01_unipaths.dir/src/paths/long/large/ExtractReads.cc.o
[ 85%] Building CXX object CMakeFiles/04_patching.dir/src/paths/long/large/GapToyTools2.cc.o
[ 86%] Building CXX object CMakeFiles/02_qgraph.dir/src/paths/long/ShortKmerReadPather.cc.o
[ 87%] Building CXX object CMakeFiles/04_patching.dir/src/paths/long/large/GapToyTools4.cc.o
[ 88%] Building CXX object CMakeFiles/01_unipaths.dir/src/paths/long/large/ReadNameLookup.cc.o
[ 88%] Building CXX object CMakeFiles/02_qgraph.dir/src/paths/long/large/Repath.cc.o
[ 88%] Building CXX object CMakeFiles/04_patching.dir/src/paths/long/large/GapToyTools5.cc.o
[ 88%] Building CXX object CMakeFiles/01_unipaths.dir/src/paths/long/large/Samples.cc.o
[ 89%] Building CXX object CMakeFiles/01_unipaths.dir/src/system/Crash.cc.o
[ 90%] Building CXX object CMakeFiles/02_qgraph.dir/src/system/Crash.cc.o
[ 91%] Building CXX object CMakeFiles/04_patching.dir/src/paths/long/large/Unsat.cc.o
[ 91%] Linking CXX executable bin/02_qgraph
/usr/bin/ld: cannot find -llib
collect2: error: ld returned 1 exit status
make[2]: *** [bin/02_qgraph] Error 1
make[1]: *** [CMakeFiles/02_qgraph.dir/all] Error 2
[ 91%] Linking CXX executable bin/01_unipaths
/usr/bin/ld: cannot find -llib
collect2: error: ld returned 1 exit status
make[2]: *** [bin/01_unipaths] Error 1
make[1]: *** [CMakeFiles/01_unipaths.dir/all] Error 2
[ 91%] Linking CXX executable bin/04_patching
/usr/bin/ld: cannot find -llib
collect2: error: ld returned 1 exit status
make[2]: *** [bin/04_patching] Error 1
make[1]: *** [CMakeFiles/04_patching.dir/all] Error 2
make: *** [all] Error 2

**Comment by gonzalogacc** [comment]
Hi Scott. 
Please try set the complete path to the libjemalloc.so file should look something like this:
-D MALLOC_LIBRARY=/afs/crc.nd.edu/user/s/ssmall2/programs_that_work/jemalloc-4.2.1/lib/libjemalloc.so
Let me know how it goes.
Best
Gonza.-

**Comment by stsmall** [comment]
Hi Gonza,
That worked. Compiled with no errors and I now have: 01_unipaths  02_qgraph	03_clean  04_patching  05_simplify  06_scaffolding, in bin. 
thank you,
Scott
