### ISSUE TITLE
Resume checkpoints in w2rap-contigger?

### ISSUE THREAD

**Issue by mht85** [bioinfologics/w2rap-contigger#40]
Hi,

I'm running w2rap-contigger on a HPC and have limited walltime for each job. Is it possible to resume from a certain checkpoint during the run so I can perhaps split jobs into several smaller tasks?

Thanks.
mht

**Comment by jonwright99** [comment]
Hi @mht85,
The contigger can be run step-by-step using the parameters ```--from_step``` and ```--to_step``` so to run step 1 only you would use ```--from_step 1 --to_step 1```. Intermediate files are dumped from the previous step to be used in the next step. Some of the steps are quicker than others with step 6 being the longest. 
Best,
Jon

**Comment by mht85** [comment]
Cool, good to know. I'll give it a try!
