### ISSUE TITLE
w2rap-contigger memory issues / advices to run w2rap

### ISSUE THREAD

**Issue by AMMMachado** [bioinfologics/w2rap-contigger#42]
Hi @jonwright99 and @bjclavijo

Could you please give me some advices to deal with the w2rap pipeline. 
I'm using the w2rap pipeline to assembly a mammal genome (+-2.9GB).
I'm working in a cluster with 512Gb ram and 32 cpus.

I have 3 short read libraries (total +-800GB) with insert sizes between 400 and 500bp. (Kat hist's are below)
library 1
[mde_l1_hist.pdf](https://github.com/bioinfologics/w2rap/files/3195175/mde_l1_hist.pdf)
library 2
[mde_l2_hist.pdf](https://github.com/bioinfologics/w2rap/files/3195176/mde_l2_hist.pdf)
library 3
[mde_l3_hist.pdf](https://github.com/bioinfologics/w2rap/files/3195177/mde_l3_hist.pdf)
All libraries
[mde_l1_l2_l3 (1).pdf](https://github.com/bioinfologics/w2rap/files/3195181/mde_l1_l2_l3.1.pdf)

All the libraries were quality controlled and trimmed with Trimmomatic. 
One of this libraries were done to perform 10x, mde_l3 . 
Once we obtained short molecular lengths, we decided use it as short reads and posteriorly in re-scaffolding phase with arcs.

Before run the command below (using this docker https://hub.docker.com/r/villegar/w2rap)  i runned all steps mentioned in your tutorial, and all pipeline steps are working perfectly. 
We are using the command:
singularity exec /share/apps/singularity/w2rap.simg w2rap-contigger -t 30 -m 400 -r mde_l1_1_1.fastq,mde_l1_2_1.fastq,mde_l2_1_1.fastq,mde_l2_2_1.fastq,mde_l3_1_1.fastq,mde_l3_2_1.fastq -o mde_contigs_200k --min_freq 20 -p mde_k200 -d 32 --dump_all 1 
 
In the step 2 I'm having the same problem of #27   issue.
"terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc"

To deal with this issue i removed the 10x library, decreasing the coverage and the memory needed (perform the assembly with 1 and 2 library (+-50x - kat hist peak).
Command: 
singularity exec /share/apps/singularity/w2rap.simg w2rap-contigger -t 30 -m 400 -r mde_l1_1_1.fastq,mde_l1_2_1.fastq,mde_l2_1_1.fastq,mde_l2_2_1.fastq -o mde_contigs_200k --min_freq 12 -p mde_k200 -d 32 --dump_all 1
library 1and 2 
[mde_l1_l2_hist.pdf](https://github.com/bioinfologics/w2rap/files/3195184/mde_l1_l2_hist.pdf)
However, the program gave me the same error ("terminate called after throwing an instance of 'std::bad_alloc';what():  std::bad_alloc")

Now, i'm considering three other options to solve the problem:

1º. increase the --min_freq can be applied without lose to many information?. What value do you recommend for this situation?
2º. Subsampling the datasets (e.g. with kat or other program) and run the assembly. 
3º. Remove the polymorphic reads, first peak (small one). I can perform this with kat? 

What do you think about this situation?

Best Regards 
 André

**Comment by jonwright99** [comment]
Hi Andre,

It looks like you're running out of memory, even when only using libraries 1 and 2. I would try assembling with library 2 on it's own as you have ~45x coverage from this library which should be plenty. Set the min-freq to 10. If this fails you'll need to subsample the input even more.  

Best regards,
Jon

**Comment by AMMMachado** [comment]
Hi @jonwright99,
To test the program, I tried mde_l1 library ( the small one) and was concluded with success.
Following your advice, now im running the mde_l2 library, alone. 
I dont know if the datasets have high coverage regions. I’m thinking if  I can concatenate all libraries, run the error correction (allpaths module, bfc or other)  followed by in silico normalization to 50x (e.g. Bbnorm)  and after run the w2rap.
What you think about it? What is your advice ?

Best Regards 
André

**Comment by shamshad1987** [comment]
Hello All,
Is there any pause option in this program? For example, if we are running it on a supercomputer where any job can run only for 24 hours, so it can be paused and resumed from where it was paused. Thanks

**Comment by shamshad1987** [comment]
I am having the same issue at step 2 probably due to low memory. I am using a system with 256 GB of RAM, trying to assemble a genome of size ~700mb and using PE-150 bp libraries. Thanks
Pleas see the attached screenshot of command line I provided.

![image](https://user-images.githubusercontent.com/50191266/58156199-26464480-7ca8-11e9-8812-e850233c9f39.png)

**Comment by jonwright99** [comment]
@AMMMachado, you could try the normalisation steps you outline but we don't have much experience with these tools as we tend to run w2rap without error correction or normalisation. We'd be interested to hear how you get on though.

**Comment by jonwright99** [comment]
@shamshad1987, yes that is certainly a memory issue. You'll need to sub-sample your data if you want to assemble it on a 256Gb node. You should aim for ~45x read coverage.

**Comment by AMMMachado** [comment]
@jonwright99 and @bjclavijo , i tried several normalization and sub sampling steps , until the program finalize the assembly. 
With the mde_2 library alone, as you suggested , the program became out of memory.

At the moment, my “final” dataset have 40x, mde_1+mde_2 , normalized at 40x with bbnorm. 

Kat hist; without normalization
[mde_l1_l2_hist.pdf](https://github.com/bioinfologics/w2rap-contigger/files/3252045/mde_l1_l2_hist.pdf)

Kat hist; with normalization
[mde_l1_l2_40x_hist.pdf](https://github.com/bioinfologics/w2rap-contigger/files/3252046/mde_l1_l2_40x_hist.pdf)

Apparently, i’m not losing to many information.

 Kat comp;
![mde_l12_te_40x_200k](https://user-images.githubusercontent.com/24585998/58875304-1163ab00-86c3-11e9-9b49-61376e1ea4dd.png)

However my assembly seems very fragmented. N50 28kb, and read back mapping >85% (reads non-normilzed), total buscos between 88 and 91 %  (in several databases) , being the fragmented rate between 20 and 26 %.

My reads are paired-ed 150, insert size 350.
How can I decrease the level of fragmentation of the assembly ?
Which K (from step 3)  do you recommend in this situation ? Maybe lower valeus , e.g 180, 160 , 150 ?
If I re-scaffolding with total mde_1+mde_2 reads and soap scaffolding module, can I increase the contiguity and content of my assembly and decrease the level of fragmentation?  
How can i remove the first peak, heterozygote peak , from the dataset with kat?

Best Regards 
André

**Comment by jonwright99** [comment]
Hi Andre,

It's difficult to advise you here as we never use techniques such as read normalisation to reduce the input read dataset as this obviously removes information from the reads before assembly. It looks like the fragmentation and general "incompleteness" of your assembly is due to what you are doing here. I don't think trying a different kmer size will help. Scaffolding may increase the contiguity of the assembly but will not increase the content as scaffolding only joins existing contigs, it will not introduce content that has potentially been excluded by your pre-processing steps.

You can use the 'sect' tool in KAT to identify content that represents the first peak. kat sect takes an assembly and a read dataset (the one you used to generate the assembly) and generates a FASTA-like output containing each sequence and the kmer coverage of each base in each sequence. There is also a summary file showing mean kmer coverage for each sequence. You should be able to split the assembly into sequences with approx. 30x coverage (from the first heterozygous peak) and those with approx. 60x coverage (from the homozygous peak).

I hope this helps.
Jon

**Comment by bjclavijo** [comment]
I'm closing this one as advise was given and it seems to be stalled.
