### ISSUE TITLE
Segfault during Step 6: removing small components

### ISSUE THREAD

**Issue by melop** [bioinfologics/w2rap-contigger#43]
Hello,

w2rap-contigger (downloaded 2019-10-24) ran Segfault during step 6 on a small dataset. 
I am attaching the log file and the fastq files that caused the error.
[assembly.log](https://github.com/bioinfologics/w2rap-contigger/files/3813771/assembly.log)
[R1.fq.gz](https://github.com/bioinfologics/w2rap-contigger/files/3813780/R1.fq.gz)
[R2.fq.gz](https://github.com/bioinfologics/w2rap-contigger/files/3813781/R2.fq.gz)

Best Regards,
R. Cui

**Comment by jonwright99** [comment]
Hi, Can you give a bit more information about what you are trying to do? Your read files are pretty small so are you trying to assemble a short section of sequence or are these reads a subset of a larger dataset?
Thanks,
Jon

**Comment by melop** [comment]
Dear Jon,

     thank you for your reply. I was trying to extract reads from targeted regions of the genome, and perform a local assembly. 

Best,
R. Cui

**Comment by melop** [comment]
Dear Jon,

I have tested now using another two independent datasets from the same target region from the same species (but different individual). The program segfault at the same step. 
I am attaching these two additional datasets for you to look at.
I notice that by setting --min_freq to 4 the program can finish, but only very short contigs were returned and N50 is "0".
[debug.tar.gz](https://github.com/bioinfologics/w2rap-contigger/files/3818651/debug.tar.gz)

Best,
Ray

**Comment by jonwright99** [comment]
Hi Ray,
Have you tried using a different assembler on these datasets, especially the ones that fail. It could be that this region is just not able to be assembled with the data you have. W2rap is designed to efficiently assemble large, complex genomes so probably isn't the tool for small local assemblies, I would suggest something much simpler like velvet would do a better job.
Best,
Jon

**Comment by melop** [comment]
Hi Jon,

I tested 6 such datasets from other species, including species that are closely related, and they all worked with w2rap-contigger. I will also try velvet to see if they assemble. 
Thanks,
Ray

**Comment by melop** [comment]
Hi Jon,
Velvet was able to run through without errors. But yeah the contigs tend to be very short as expected. Does that explain the segfault of w2rap-contigger perhaps?

Ray

**Comment by jonwright99** [comment]
Great! The segfault you are seeing in the contigger is because no contigs are being generated at an earlier stage. This isn't ideal and we've fixed the issue in our current development branch. We're planning to make the development branch the master branch once we've finished up our latest changes and fixes, hopefully soon.
