### ISSUE TITLE
Some trouble with CP_MAX_QDIFF value !

### ISSUE THREAD

**Issue by Arno75** [bioinfologics/w2rap-contigger#5]
Hello,
i've try to run w2rap-contigger on my illumina data set. The first steps (01_unipaths, 02_qgraph and 03_clean) are ok. But in the patching process , i've got some trouble with CP_MAX_QDIFF value, and this message in the output "Illegal value for CP_MAX_QDIFF". This variable is define in the patching script , and can't be modified.
Thanks in advance for your help.

Arnaud

**Comment by gonzalogacc** [comment]
Hi Arnaud.
Can you describe your data a bit? Insert size distribution, kmer spectra, quality profile, duplication rate, etc.
Best.
Gonza.-

**Comment by Arno75** [comment]
It's a Paired End (2X300pb - Insert Size ~ 600pb) library, for an eukaryotic genome (heterozygous) of 1,5Gb Size. The duplication rate is less than 1% and the average quality score is near 31. 
Yes i've tryed to modify it , but it has no effect.
I do not understand exactly what it does. 
The maximum accepted quality difference between two reads of a pair??? ... i suppose.

**Comment by bjclavijo** [comment]
What is your rationale to modify this? this is the maximum discrepancy between a pair and the rest of the cluster for read correction.

**Comment by Arno75** [comment]
I have no real reason to modife this variable , it's already define in the script. But the error message said that it's an illegal value.

**Comment by bjclavijo** [comment]
Ok, so you are not modifying the code at all and when running you're getting that error? As far as I know we haven't changed anything on that part of the code for a while.
Can you tell us which compiler, os, etc you're using? If you made any modifications at all to the code, that would be needed too, as a full transcript of the output error.

**Comment by Arno75** [comment]
GCC: (GNU) 4.4.7
  
and this is the entire error message  ...

Set computational resources
SYSTEM INFO
- OS: Linux :: 2.6.32-573.22.1.el6.x86_64 :: #1 SMP Wed Mar 23 03:35:39 UTC 2016
- node name: etna14.genoscope.cns.fr
- hardware type: x86_64
- cache size: 30720 KB
- cpu MHz: 2593.477
- cpu model name: Intel(R) Xeon(R) CPU E7-4860 v2 @ 2.60GHz
- physical memory: 3029.55 GB

mar. mai 24 17:45:51 2016: finding unsatisfieds
mar. mai 24 17:46:22 2016: creating multiplicity std::map
mar. mai 24 17:46:24 2016: economizing links
mar. mai 24 17:46:25 2016: forming neighborhoods
mar. mai 24 17:47:34 2016: forming initial clusters
mar. mai 24 17:47:52 2016: start sort
1.86 seconds used sorting
mar. mai 24 17:47:54 2016: merging clusters
xs.size( ) = 3519942
6.96 minutes used merging
xs.size( ) = 1553913
mar. mai 24 17:55:03 2016: start overlap-based merging
mar. mai 24 18:00:41 2016: start overlap-based merging
LR.size( ) = 1500659
LR.size( ) = 750897
mar. mai 24 18:08:35 2016: now processing 750897 blobs
mar. mai 24 18:08:35 2016: memory in use = 21.25 GB, peak = 20.76 GB

Fatal error (pid=119313) at mar. mai 24 18:08:35 2016:
Illegal value for CP_MAX_QDIFF.

**Comment by gonzalogacc** [comment]
Have you modified the CP_MAX_QDIFF variable at any point?

**Comment by Arno75** [comment]
No, at the beginning i do not !
But after reading this error message , i tried to change it whithout succes.

**Comment by gonzalogacc** [comment]
Try using Gcc 5.2+ and let me know how it goes.

**Comment by bjclavijo** [comment]
Hi Arnaud, any news on this?

**Comment by bjclavijo** [comment]
Hi Arnaud, as I have not heard back I'll close this one, If there are still any problems you can comment here and we'll re-open this if needed.
