### ISSUE TITLE
Step 3 crash

### ISSUE THREAD

**Issue by mlcossette9224** [bioinfologics/w2rap-contigger#50]
I am getting the following error on step 3

--== Step 3: Repathing to second (large K) graph ==--
Tue Mar 02 13:15:06 2021: beginning repathing 31790560 edges from K=60 to K2=64
Tue Mar 02 13:15:06 2021: constructing places from 1308014986 paths
Tue Mar 02 13:15:12 2021: 1265069099 / 1308014986 reads pathed, 173319806 spanning junctions
Tue Mar 02 13:20:49 2021: sorting 1264197670 places
Tue Mar 02 14:03:45 2021: 77032864 unique places
Tue Mar 02 14:03:45 2021: building all
Tue Mar 02 14:08:44 2021: calling LongReadsToPaths
Fatal error (pid=16780) at Tue Mar 02 14:08:44 2021:
Illegal value 64 for K in BigK dispatcher.

What should I do?

**Comment by bjclavijo** [comment]
You seem to be using 64 as the value for large_K. Allowed values are: {20,     24,     28,     32,     40,     48,     60,     72,     80,     84,    88,     96,     100,    108,    116,    128,    136,    144,    152,    160,    168,     172,    180,    188,    196,    200,    208,    216,    224,    232,    240,     260,    280,    300,    320,    368,    400,    500,    544,    640,    720,     1000,   1200,   1600,   2000,   4000,   10000}

Keep in mind you want that value to be larger than small_k and smaller than your read size.

Best,

bj
