### ISSUE TITLE
Output the contig overlap graph in GFA format

### ISSUE THREAD

**Issue by sjackman** [bioinfologics/w2rap-contigger#8]
[Graphical Fragment Assembly (GFA)](https://github.com/pmelsted/GFA-spec) format describes the contig overlap graph of a genome sequence assembly. [Bandage](https://rrwick.github.io/Bandage/) can be used to visualize this graph. The format specification was originally drafted by Heng Li and is now community-maintained and nearing completeness. The format allows optional fields similarly to the SAM spec.

**Comment by bjclavijo** [comment]
Hi Shaun, I am working on this, it is actually quite helpful to use GFA as an exchange format. Next updated version (quite soon, I hope) will have some GFA support, even if not perfect.

**Comment by bjclavijo** [comment]
Leaving this open till the support is on the main branch and tested...

**Comment by sjackman** [comment]
That's great! Thanks, Bernardo. I'm excited to see more interoperability between assembler pipelines.

**Comment by bjclavijo** [comment]
This functionality is provided by hbv2gfa in older branches and will be provided directly in the next release.
